// Each entry: display name, PokeAPI sprite slug, and the list of common named sets.
// "Other" is added automatically by the app — don't list it here.
const POKEMON_DATA = [
  { name: "Cresselia", sprite: "cresselia", sets: ["Scarf", "Non-Icy Wind Leftovers", "Icy Wind Leftovers", "Kee"] },
  { name: "Primarina", sprite: "primarina", sets: ["Custap", "Sitrus", "Specs", "Pixie Plate", "Wacan", "Mental Herb"] },
  { name: "Celesteela", sprite: "celesteela", sets: ["Custap", "Mental Herb", "Occa", "Sitrus", "Band", "Specs"] },
  { name: "Dragapult", sprite: "dragapult", sets: ["Specs", "Wisp Sub Disable", "Band", "Curse", "Dragon Dance Weakness Policy"] },
  { name: "Garchomp", sprite: "garchomp", sets: ["Life Orb", "Scarf", "Band", "Custap", "Haban"] },
  { name: "Metagross", sprite: "metagross", sets: ["Scarf", "Assault Vest", "Endure Weakness Policy", "Band", "Air Balloon", "Occa"] },
  { name: "Spectrier", sprite: "spectrier", sets: ["Life Orb", "Helmet", "Sitrus Taunt", "Disable", "Specs", "Weakness Policy"] },
  { name: "Tapu Fini", sprite: "tapu-fini", sets: ["Scarf", "Wiki", "Leftovers", "Weakness Policy", "Specs", "Sitrus"] },
  { name: "Darmanitan-Galar", sprite: "darmanitan-galar", sets: ["Scarf", "Band", "Weakness Policy Zen", "Def Invested Choiced"] },
  { name: "Entei", sprite: "entei", sets: ["Pressure Stall", "Assault Vest", "Band"] },
  { name: "Ferrothorn", sprite: "ferrothorn", sets: ["Iron Defense + Body Press", "Band", "Custap"] },
  { name: "Landorus-Therian", sprite: "landorus-therian", sets: ["Assault Vest", "Bulk Up", "Band", "SpDef Band", "Scarf"] },
  { name: "Porygon-Z", sprite: "porygon-z", sets: ["Life Orb", "Specs", "Custap", "Scarf", "Helmet"] },
  { name: "Urshifu-Single-Strike", sprite: "Urshifu-Single-Strike", sets: ["Band", "Taunt Life Orb", "Bulky Chople", "Fast Chople", "Assault Vest", "Liechi", "Scarf", "Custap"] },
  { name: "Volcarona", sprite: "volcarona", sets: ["Specs", "Mental Herb", "Life Orb", "Kee", "Custap"] },
  { name: "Zeraora", sprite: "zeraora", sets: ["Band", "Assault Vest", "Life Orb", "Weakness Policy"] },
  { name: "Aromatisse", sprite: "aromatisse", sets: ["Def Helmet", "SpDef Helmet", "Wiki"] },
  { name: "Azumarill", sprite: "azumarill", sets: ["Assault Vest", "Life Orb", "Stall", "Band", "Belly Drum"] },
  { name: "Crustle", sprite: "crustle", sets: ["Band", "Lum", "Mental Herb", "Custap"] },
  { name: "Sylveon", sprite: "sylveon", sets: ["Specs", "Mental Herb + Yawn", "Life Orb + Yawn", "Custap"] },
  { name: "Tapu Bulu", sprite: "tapu-bulu", sets: ["Grassy Seed Wood Hammer + Leech Seed", "Grassy Seed Substitute + Disable", "Grassy Seed Dazzling Gleam", "Grassy Seed Bulk Up", "Hybrid of above moves"] },
];
