// Each entry: display name, PokeAPI sprite slug, and the list of common named sets.
// "Other" is added automatically by the app — don't list it here.
const POKEMON_DATA = [
  { name: "Cresselia", sprite: "cresselia", sets: ["Scarf", "Non-Icy Wind Leftovers", "Icy Wind Leftovers", "Kee"] },
  { name: "Primarina", sprite: "primarina", sets: ["Custap", "Sitrus", "Specs", "Pixie Plate", "Wacan", "Mental Herb"] },
  { name: "Celesteela", sprite: "celesteela", sets: ["Custap", "Mental Herb", "Occa", "Sitrus", "Band", "Specs"] },
  { name: "Dragapult", sprite: "dragapult", sets: ["Specs", "Wisp Sub Disable", "Band", "Curse", "Dragon Dance Weakness Policy"] },
  { name: "Garchomp", sprite: "garchomp", sets: ["Life Orb", "Scarf", "Band", "Custap", "Haban"] },
  { name: "Metagross", sprite: "metagross", sets: ["Scarf", "Assault Vest", "Endure Weakness Policy", "Band", "Air Balloon", "Occa"] },
  { name: "Spectrier", sprite: "spectrier", sets: ["Life Orb", "Helmet", "Sitrus Taunt", "Disable", "Specs", "Weakness Policy"] },
  { name: "Tapu Fini", sprite: "tapu-fini", sets: ["Scarf", "Wiki", "Leftovers", "Weakness Policy", "Specs", "Sitrus"] },
  { name: "Darmanitan-Galar", sprite: "darmanitan-galarian-standard", sets: ["Scarf", "Band", "Weakness Policy Zen", "Def Invested Choiced"] },
  { name: "Entei", sprite: "entei", sets: ["Pressure Stall", "Assault Vest", "Band"] },
  { name: "Ferrothorn", sprite: "ferrothorn", sets: ["Iron Defense + Body Press", "Band", "Custap"] },
  { name: "Landorus-Therian", sprite: "landorus-therian", sets: ["Assault Vest", "Bulk Up", "Band", "SpDef Band", "Scarf"] },
  { name: "Porygon-Z", sprite: "porygon-z", sets: ["Life Orb", "Specs", "Custap", "Scarf", "Helmet"] },
  { name: "Urshifu-Single-Strike", sprite: "Urshifu-Single-Strike", sets: ["Band", "Taunt Life Orb", "Bulky Chople", "Fast Chople", "Assault Vest", "Liechi", "Scarf", "Custap"] },
  { name: "Volcarona", sprite: "volcarona", sets: ["Specs", "Mental Herb", "Life Orb", "Kee", "Custap"] },
  { name: "Zeraora", sprite: "zeraora", sets: ["Band", "Assault Vest", "Life Orb", "Weakness Policy"] },
  { name: "Aromatisse", sprite: "aromatisse", sets: ["Def Helmet", "SpDef Helmet", "Wiki"] },
  { name: "Azumarill", sprite: "azumarill", sets: ["Assault Vest", "Life Orb", "Stall", "Band", "Belly Drum"] },
  { name: "Crustle", sprite: "crustle", sets: ["Band", "Lum", "Mental Herb", "Custap"] },
  { name: "Sylveon", sprite: "sylveon", sets: ["Specs", "Mental Herb + Yawn", "Life Orb + Yawn", "Custap"] },
  { name: "Tapu Bulu", sprite: "tapu-bulu", sets: ["Grassy Seed Wood Hammer + Leech Seed", "Grassy Seed Substitute + Disable", "Grassy Seed Dazzling Gleam", "Grassy Seed Bulk Up", "Hybrid of above moves"] },
  { name: "Tapu Koko", sprite: "tapu-koko", sets: ["Electric Seed Offense (2+ attacks)", "Electric Seed Stall (<=1 attacks)", "Physical/Mixed Life Orb Charge", "Electric Seed Thief", "Special Life Orb"] },
  { name: "Togekiss", sprite: "togekiss", sets: ["Resist Berry Counter", "Charm Kee", "Scarf Counter", "Fast Maranga", "Scarf", "Mental Herb", "Slow Maranga"] },
  { name: "Urshifu-Rapid-Strike", sprite: "Urshifu-Rapid-Strike", sets: ["Life Orb", "Assault Vest", "Band", "Iron Defense + Body Press", "Wacan", "Endure Weakness Policy"] },
  { name: "Volcanion", sprite: "volcanion", sets: ["Sitrus", "Air Balloon", "Custap", "Scarf", "Specs", "Assault Vest"] },
  { name: "Zarude", sprite: "zarude", sets: ["Weakness Policy Encore", "Band", "Weakness Policy Snarl", "Scarf", "Assault Vest"] },
  { name: "Zapdos", sprite: "zapdos", sets: ["Offensive Life Orb", "Pressure Stall", "Maranga", "Custap", "Specs", "Stall Life Orb"] },
  { name: "Kyurem", sprite: "kyurem", sets: ["Special Weakness Policy", "Roseli", "Chople", "Haban Noble Roar", "Specs", "Scarf", "Haban Offensive", "Assault Vest", "Physical Weakness Policy"] },
  { name: "Tyranitar", sprite: "tyranitar", sets: ["Band", "Weakness Policy", "Chople", "Assault Vest", "Custap"] },
  { name: "Moltres-Galar", sprite: "moltres-galar", sets: ["Custap", "Sitrus", "Helmet"] },
  { name: "Regieleki", sprite: "regieleki", sets: ["Specs"] },
  { name: "Venusaur", sprite: "venusaur", sets: ["Leech Seed", "Custap"] },
  { name: "Landorus-Incarnate", sprite: "landorus-incarnate", sets: ["Fast Life Orb", "Bulky Life Orb", "Specs", "Band", "Scarf"] },
  { name: "Naganadel", sprite: "naganadel", sets: ["Specs", "Life Orb"] },
  { name: "Aggron", sprite: "aggron", sets: ["Band", "Scarf", "Custap"] },
  { name: "Rillaboom", sprite: "rillaboom", sets: ["Life Orb", "Grassy Seed Offensive", "Leech Seed", "Assault Vest"] },
  { name: "Regidrago", sprite: "regidrago", sets: ["Custap", "Band", "Haban", "Assault Vest"] },
  { name: "Rhyperior", sprite: "rhyperior", sets: ["Band", "Custap", "Assault Vest"] },
  { name: "Arcanine", sprite: "arcanine", sets: ["Band", "Scarf", "Life Orb", "Assault Vest", "Stall"] },
  { name: "Heatran", sprite: "heatran", sets: ["Specs", "Scarf", "Iron Defense + Body Press", "Air Balloon Offensive", "Custap"] },
  { name: "Chansey", sprite: "chansey", sets: ["Charm", "Toxic", "SpDef"] },
  { name: "Haxorus", sprite: "haxorus", sets: ["Scarf", "Band", "Roseli", "Life Orb", "Custap"] },
  { name: "Corviknight", sprite: "corviknight", sets: ["Iron Defense + Body Press", "Substitute Stall"] },
  { name: "Nihilego", sprite: "nihilego", sets: ["Power Herb", "Specs"] },
  { name: "Registeel", sprite: "registeel", sets: ["Leftovers Body Press", "Leftovers Counter", "Air Balloon", "Assault Vest"] },
  { name: "Tapu Lele", sprite: "tapu-lele", sets: ["Psychic Seed", "Custap", "Specs", "Scarf", "Weakness Policy", "Skill Swap"] },
  { name: "Magnezone", sprite: "magnezone", sets: ["Specs", "Custap", "Weakness Policy"] },
];
